highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://dogun-kim.github.io/
author: Dogun Kim

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: ""
title: Dogun Kim
name: Dogun Kim
email: dgkimk93@gmail.com
email_full: mailto:dgkimk93@gmail.com
website: github.io
website_full: https://Dogun-Kim.github.io/
github: https://github.com/DoGunKIM93
google_scholar: https://scholar.google.com/citations?hl=en&user=mC9yZBAAAAAJ
linkedin: https://www.linkedin.com/in/dogun-kim-501473142/
twitter: twitter
tel: +44 0000 000000
tel_full: tel:+440000000000
address:
  street:
  postcode:
  city:
  country:
# needed for travis-ci build
exclude: [vendor]
